export const GET_USER_CONTEXT = 'GET_USER_CONTEXT';
export const SET_USER_CONTEXT = 'SET_USER_CONTEXT';
export const DELETE_USER_CONTEXT = 'DELETE_USER_CONTEXT';

export const FETCH_TRUCKS_PENDING = 'FETCH_TRUCKS_PENDING';
export const FETCH_TRUCKS_SUCCESS = 'FETCH_TRUCKS_SUCCESS';
export const FETCH_TRUCKS_ERROR = 'FETCH_TRUCKS_ERROR';
