export const GET_USER_CONTEXT = 'GET_USER_CONTEXT';
export const SET_USER_CONTEXT = 'SET_USER_CONTEXT';
export const DELETE_USER_CONTEXT = 'DELETE_USER_CONTEXT';

export const FETCH_CARS_PENDING = 'FETCH_CARS_PENDING';
export const FETCH_CARS_SUCCESS = 'FETCH_CARS_SUCCESS';
export const FETCH_CARS_ERROR = 'FETCH_CARS_ERROR';